# Generated by Django 5.0.1 on 2024-04-11 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bmirecord',
            name='name',
        ),
    ]
