# Generated by Django 5.0.1 on 2024-04-11 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0002_remove_bmirecord_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bmirecord',
            name='bmi',
        ),
    ]
